spring:
  application:
    name: objectmorph-auth
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: objectmorph-client
            client-secret: hMYLCSLU7LZMtTgx4ogfYgXINQiba4NB
            scope: openid,profile,email
            redirect-uri: '{baseUrl}/login/oauth2/code/keycloak'
        provider:
          keycloak:
            issuer-uri: "http://localhost:8088/realms/objectmorph-realm"
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8088/realms/objectmorph-realm
          audiences: objectmorph-auth
logging:
  level:
    root: INFO
    # General Spring Security logging
    org.springframework.security: DEBUG
    # Detailed logging for OAuth2 and OIDC components
    org.springframework.security.oauth2: DEBUG
    # Logging for JWT decoding and validation
    org.springframework.security.oauth2.server.resource.authentication: DEBUG
    # Detailed logging for web request processing within Spring Security filter chain
    org.springframework.security.web.FilterChainProxy: DEBUG
    # Logging for HTTP requests made by Spring's internal RestTemplate components (e.g., fetching JWKS)
    org.springframework.web.client.RestTemplate: DEBUG
    # If using Keycloak-specific libraries (though the official adapters are deprecated in favor of Spring Security)
    org.keycloak: DEBUG
  pattern:
    console: "[%level] %d{yyyy-MM-dd HH:mm:ss} - %logger{1.} - %msg%n"
server:
  port: 8084
  max-http-request-header-size: 65000
  servlet:
    session:
      timeout: 600s
