apiVersion: apps/v1
kind: Deployment
metadata:
  name: objectmorph-auth
spec:
  selector:
      matchLabels:
        app: objectmorph-auth
  template:
    metadata:
      labels:
        app: objectmorph-auth
    spec:
      containers:
        - name: objectmorph-auth
          image: docker.io/ennahdi/objectmorph-auth:0.1.7-SNAPSHOT
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: CLIENT_SECRET
              value: MPq1VZN1ZCNFmBFsqAgvCihRv4p2fVsn